// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/broker.proto

package brokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeRequest) Reset() {
	*x = CreateExchangeRequest{}
	mi := &file_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRequest) ProtoMessage() {}

func (x *CreateExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRequest.ProtoReflect.Descriptor instead.
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeResponse) Reset() {
	*x = CreateExchangeResponse{}
	mi := &file_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeResponse) ProtoMessage() {}

func (x *CreateExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeResponse.ProtoReflect.Descriptor instead.
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExchangeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExchangeRequest) Reset() {
	*x = DeleteExchangeRequest{}
	mi := &file_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExchangeRequest) ProtoMessage() {}

func (x *DeleteExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExchangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExchangeResponse) Reset() {
	*x = DeleteExchangeResponse{}
	mi := &file_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExchangeResponse) ProtoMessage() {}

func (x *DeleteExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExchangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{3}
}

type RegisterQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Durable       bool                   `protobuf:"varint,3,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete    bool                   `protobuf:"varint,4,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Filters       []string               `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterQueueRequest) Reset() {
	*x = RegisterQueueRequest{}
	mi := &file_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterQueueRequest) ProtoMessage() {}

func (x *RegisterQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterQueueRequest.ProtoReflect.Descriptor instead.
func (*RegisterQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterQueueRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *RegisterQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RegisterQueueRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *RegisterQueueRequest) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *RegisterQueueRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *RegisterQueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type RegisterQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterQueueResponse) Reset() {
	*x = RegisterQueueResponse{}
	mi := &file_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterQueueResponse) ProtoMessage() {}

func (x *RegisterQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterQueueResponse.ProtoReflect.Descriptor instead.
func (*RegisterQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterQueueResponse) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *RegisterQueueResponse) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_proto_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQueueRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *DeleteQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_proto_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{7}
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{8}
}

func (x *PublishRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *PublishRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{9}
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{10}
}

func (x *FetchRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *FetchRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *FetchRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *FetchRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DeliveryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryMessage) Reset() {
	*x = DeliveryMessage{}
	mi := &file_proto_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMessage) ProtoMessage() {}

func (x *DeliveryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMessage.ProtoReflect.Descriptor instead.
func (*DeliveryMessage) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{11}
}

func (x *DeliveryMessage) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryMessage) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *DeliveryMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeliveryMessage) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryMessage       `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{12}
}

func (x *FetchResponse) GetDelivery() *DeliveryMessage {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type SFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SFetchRequest) Reset() {
	*x = SFetchRequest{}
	mi := &file_proto_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFetchRequest) ProtoMessage() {}

func (x *SFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFetchRequest.ProtoReflect.Descriptor instead.
func (*SFetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{13}
}

func (x *SFetchRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *SFetchRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *SFetchRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type SFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryMessage       `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SFetchResponse) Reset() {
	*x = SFetchResponse{}
	mi := &file_proto_broker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFetchResponse) ProtoMessage() {}

func (x *SFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFetchResponse.ProtoReflect.Descriptor instead.
func (*SFetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{14}
}

func (x *SFetchResponse) GetDelivery() *DeliveryMessage {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_broker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{15}
}

func (x *AckRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *AckRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *AckRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AckRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_broker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{16}
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_proto_broker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{17}
}

func (x *NackRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *NackRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *NackRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *NackRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_proto_broker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{18}
}

type AddConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConsumerRequest) Reset() {
	*x = AddConsumerRequest{}
	mi := &file_proto_broker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConsumerRequest) ProtoMessage() {}

func (x *AddConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConsumerRequest.ProtoReflect.Descriptor instead.
func (*AddConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{19}
}

func (x *AddConsumerRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *AddConsumerRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *AddConsumerRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type AddConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConsumerResponse) Reset() {
	*x = AddConsumerResponse{}
	mi := &file_proto_broker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConsumerResponse) ProtoMessage() {}

func (x *AddConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConsumerResponse.ProtoReflect.Descriptor instead.
func (*AddConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{20}
}

type DisconnectConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeName  string                 `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	QueueName     string                 `protobuf:"bytes,2,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectConsumerRequest) Reset() {
	*x = DisconnectConsumerRequest{}
	mi := &file_proto_broker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectConsumerRequest) ProtoMessage() {}

func (x *DisconnectConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectConsumerRequest.ProtoReflect.Descriptor instead.
func (*DisconnectConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{21}
}

func (x *DisconnectConsumerRequest) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *DisconnectConsumerRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DisconnectConsumerRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type DisconnectConsumerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectConsumerResponse) Reset() {
	*x = DisconnectConsumerResponse{}
	mi := &file_proto_broker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectConsumerResponse) ProtoMessage() {}

func (x *DisconnectConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectConsumerResponse.ProtoReflect.Descriptor instead.
func (*DisconnectConsumerResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{22}
}

var File_proto_broker_proto protoreflect.FileDescriptor

const file_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/broker.proto\x12\x06broker\"+\n" +
	"\x15CreateExchangeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16CreateExchangeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DeleteExchangeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DeleteExchangeResponse\"\xd2\x01\n" +
	"\x14RegisterQueueRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x18\n" +
	"\adurable\x18\x03 \x01(\bR\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x04 \x01(\bR\n" +
	"autoDelete\x12\x18\n" +
	"\afilters\x18\x05 \x03(\tR\afilters\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\"[\n" +
	"\x15RegisterQueueResponse\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"X\n" +
	"\x12DeleteQueueRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\"\x15\n" +
	"\x13DeleteQueueResponse\"p\n" +
	"\x0ePublishRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x11\n" +
	"\x0fPublishResponse\"\x92\x01\n" +
	"\fFetchRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\"\x89\x01\n" +
	"\x0fDeliveryMessage\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\"D\n" +
	"\rFetchResponse\x123\n" +
	"\bdelivery\x18\x01 \x01(\v2\x17.broker.DeliveryMessageR\bdelivery\"t\n" +
	"\rSFetchRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\"E\n" +
	"\x0eSFetchResponse\x123\n" +
	"\bdelivery\x18\x01 \x01(\v2\x17.broker.DeliveryMessageR\bdelivery\"\x92\x01\n" +
	"\n" +
	"AckRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vdelivery_id\x18\x03 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\tR\n" +
	"consumerId\"\r\n" +
	"\vAckResponse\"\x93\x01\n" +
	"\vNackRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vdelivery_id\x18\x03 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\tR\n" +
	"consumerId\"\x0e\n" +
	"\fNackResponse\"y\n" +
	"\x12AddConsumerRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\"\x15\n" +
	"\x13AddConsumerResponse\"\x80\x01\n" +
	"\x19DisconnectConsumerRequest\x12#\n" +
	"\rexchange_name\x18\x01 \x01(\tR\fexchangeName\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x02 \x01(\tR\tqueueName\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\"\x1c\n" +
	"\x1aDisconnectConsumerResponse2\x81\x06\n" +
	"\rBrokerService\x12O\n" +
	"\x0eCreateExchange\x12\x1d.broker.CreateExchangeRequest\x1a\x1e.broker.CreateExchangeResponse\x12O\n" +
	"\x0eDeleteExchange\x12\x1d.broker.DeleteExchangeRequest\x1a\x1e.broker.DeleteExchangeResponse\x12L\n" +
	"\rRegisterQueue\x12\x1c.broker.RegisterQueueRequest\x1a\x1d.broker.RegisterQueueResponse\x12F\n" +
	"\vDeleteQueue\x12\x1a.broker.DeleteQueueRequest\x1a\x1b.broker.DeleteQueueResponse\x12:\n" +
	"\aPublish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponse\x124\n" +
	"\x05Fetch\x12\x14.broker.FetchRequest\x1a\x15.broker.FetchResponse\x12>\n" +
	"\vStreamFetch\x12\x15.broker.SFetchRequest\x1a\x16.broker.SFetchResponse0\x01\x12.\n" +
	"\x03Ack\x12\x12.broker.AckRequest\x1a\x13.broker.AckResponse\x121\n" +
	"\x04Nack\x12\x13.broker.NackRequest\x1a\x14.broker.NackResponse\x12F\n" +
	"\vAddConsumer\x12\x1a.broker.AddConsumerRequest\x1a\x1b.broker.AddConsumerResponse\x12[\n" +
	"\x12DisconnectConsumer\x12!.broker.DisconnectConsumerRequest\x1a\".broker.DisconnectConsumerResponseB?Z=github.com/SitnikovArtem06/message-broker/gen/broker;brokerpbb\x06proto3"

var (
	file_proto_broker_proto_rawDescOnce sync.Once
	file_proto_broker_proto_rawDescData []byte
)

func file_proto_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)))
	})
	return file_proto_broker_proto_rawDescData
}

var file_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_broker_proto_goTypes = []any{
	(*CreateExchangeRequest)(nil),      // 0: broker.CreateExchangeRequest
	(*CreateExchangeResponse)(nil),     // 1: broker.CreateExchangeResponse
	(*DeleteExchangeRequest)(nil),      // 2: broker.DeleteExchangeRequest
	(*DeleteExchangeResponse)(nil),     // 3: broker.DeleteExchangeResponse
	(*RegisterQueueRequest)(nil),       // 4: broker.RegisterQueueRequest
	(*RegisterQueueResponse)(nil),      // 5: broker.RegisterQueueResponse
	(*DeleteQueueRequest)(nil),         // 6: broker.DeleteQueueRequest
	(*DeleteQueueResponse)(nil),        // 7: broker.DeleteQueueResponse
	(*PublishRequest)(nil),             // 8: broker.PublishRequest
	(*PublishResponse)(nil),            // 9: broker.PublishResponse
	(*FetchRequest)(nil),               // 10: broker.FetchRequest
	(*DeliveryMessage)(nil),            // 11: broker.DeliveryMessage
	(*FetchResponse)(nil),              // 12: broker.FetchResponse
	(*SFetchRequest)(nil),              // 13: broker.SFetchRequest
	(*SFetchResponse)(nil),             // 14: broker.SFetchResponse
	(*AckRequest)(nil),                 // 15: broker.AckRequest
	(*AckResponse)(nil),                // 16: broker.AckResponse
	(*NackRequest)(nil),                // 17: broker.NackRequest
	(*NackResponse)(nil),               // 18: broker.NackResponse
	(*AddConsumerRequest)(nil),         // 19: broker.AddConsumerRequest
	(*AddConsumerResponse)(nil),        // 20: broker.AddConsumerResponse
	(*DisconnectConsumerRequest)(nil),  // 21: broker.DisconnectConsumerRequest
	(*DisconnectConsumerResponse)(nil), // 22: broker.DisconnectConsumerResponse
}
var file_proto_broker_proto_depIdxs = []int32{
	11, // 0: broker.FetchResponse.delivery:type_name -> broker.DeliveryMessage
	11, // 1: broker.SFetchResponse.delivery:type_name -> broker.DeliveryMessage
	0,  // 2: broker.BrokerService.CreateExchange:input_type -> broker.CreateExchangeRequest
	2,  // 3: broker.BrokerService.DeleteExchange:input_type -> broker.DeleteExchangeRequest
	4,  // 4: broker.BrokerService.RegisterQueue:input_type -> broker.RegisterQueueRequest
	6,  // 5: broker.BrokerService.DeleteQueue:input_type -> broker.DeleteQueueRequest
	8,  // 6: broker.BrokerService.Publish:input_type -> broker.PublishRequest
	10, // 7: broker.BrokerService.Fetch:input_type -> broker.FetchRequest
	13, // 8: broker.BrokerService.StreamFetch:input_type -> broker.SFetchRequest
	15, // 9: broker.BrokerService.Ack:input_type -> broker.AckRequest
	17, // 10: broker.BrokerService.Nack:input_type -> broker.NackRequest
	19, // 11: broker.BrokerService.AddConsumer:input_type -> broker.AddConsumerRequest
	21, // 12: broker.BrokerService.DisconnectConsumer:input_type -> broker.DisconnectConsumerRequest
	1,  // 13: broker.BrokerService.CreateExchange:output_type -> broker.CreateExchangeResponse
	3,  // 14: broker.BrokerService.DeleteExchange:output_type -> broker.DeleteExchangeResponse
	5,  // 15: broker.BrokerService.RegisterQueue:output_type -> broker.RegisterQueueResponse
	7,  // 16: broker.BrokerService.DeleteQueue:output_type -> broker.DeleteQueueResponse
	9,  // 17: broker.BrokerService.Publish:output_type -> broker.PublishResponse
	12, // 18: broker.BrokerService.Fetch:output_type -> broker.FetchResponse
	14, // 19: broker.BrokerService.StreamFetch:output_type -> broker.SFetchResponse
	16, // 20: broker.BrokerService.Ack:output_type -> broker.AckResponse
	18, // 21: broker.BrokerService.Nack:output_type -> broker.NackResponse
	20, // 22: broker.BrokerService.AddConsumer:output_type -> broker.AddConsumerResponse
	22, // 23: broker.BrokerService.DisconnectConsumer:output_type -> broker.DisconnectConsumerResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_broker_proto_init() }
func file_proto_broker_proto_init() {
	if File_proto_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_proto = out.File
	file_proto_broker_proto_goTypes = nil
	file_proto_broker_proto_depIdxs = nil
}
