// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/broker.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	core "github.com/SitnikovArtem06/message-broker/internal/core"
	repository "github.com/SitnikovArtem06/message-broker/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteDelivery mocks base method.
func (m *MockRepository) DeleteDelivery(ctx context.Context, deliveryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDelivery", ctx, deliveryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDelivery indicates an expected call of DeleteDelivery.
func (mr *MockRepositoryMockRecorder) DeleteDelivery(ctx, deliveryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDelivery", reflect.TypeOf((*MockRepository)(nil).DeleteDelivery), ctx, deliveryID)
}

// DeleteExchange mocks base method.
func (m *MockRepository) DeleteExchange(ctx context.Context, exchangeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExchange", ctx, exchangeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExchange indicates an expected call of DeleteExchange.
func (mr *MockRepositoryMockRecorder) DeleteExchange(ctx, exchangeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExchange", reflect.TypeOf((*MockRepository)(nil).DeleteExchange), ctx, exchangeName)
}

// DeleteQueue mocks base method.
func (m *MockRepository) DeleteQueue(ctx context.Context, exchangeName, queueName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueue", ctx, exchangeName, queueName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQueue indicates an expected call of DeleteQueue.
func (mr *MockRepositoryMockRecorder) DeleteQueue(ctx, exchangeName, queueName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueue", reflect.TypeOf((*MockRepository)(nil).DeleteQueue), ctx, exchangeName, queueName)
}

// LoadState mocks base method.
func (m *MockRepository) LoadState(ctx context.Context) (repository.BrokerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadState", ctx)
	ret0, _ := ret[0].(repository.BrokerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadState indicates an expected call of LoadState.
func (mr *MockRepositoryMockRecorder) LoadState(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadState", reflect.TypeOf((*MockRepository)(nil).LoadState), ctx)
}

// MarkInFlight mocks base method.
func (m *MockRepository) MarkInFlight(ctx context.Context, deliveryID, consumerID string, attempts int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInFlight", ctx, deliveryID, consumerID, attempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInFlight indicates an expected call of MarkInFlight.
func (mr *MockRepositoryMockRecorder) MarkInFlight(ctx, deliveryID, consumerID, attempts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInFlight", reflect.TypeOf((*MockRepository)(nil).MarkInFlight), ctx, deliveryID, consumerID, attempts)
}

// MarkReady mocks base method.
func (m *MockRepository) MarkReady(ctx context.Context, deliveryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReady", ctx, deliveryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkReady indicates an expected call of MarkReady.
func (mr *MockRepositoryMockRecorder) MarkReady(ctx, deliveryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReady", reflect.TypeOf((*MockRepository)(nil).MarkReady), ctx, deliveryID)
}

// SaveDeadLetter mocks base method.
func (m *MockRepository) SaveDeadLetter(ctx context.Context, exchangeName string, letter core.DeadLetter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDeadLetter", ctx, exchangeName, letter)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDeadLetter indicates an expected call of SaveDeadLetter.
func (mr *MockRepositoryMockRecorder) SaveDeadLetter(ctx, exchangeName, letter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDeadLetter", reflect.TypeOf((*MockRepository)(nil).SaveDeadLetter), ctx, exchangeName, letter)
}

// SaveExchange mocks base method.
func (m *MockRepository) SaveExchange(ctx context.Context, exchangeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveExchange", ctx, exchangeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveExchange indicates an expected call of SaveExchange.
func (mr *MockRepositoryMockRecorder) SaveExchange(ctx, exchangeName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveExchange", reflect.TypeOf((*MockRepository)(nil).SaveExchange), ctx, exchangeName)
}

// SaveQueue mocks base method.
func (m *MockRepository) SaveQueue(ctx context.Context, exchangeName string, queue *core.Queue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQueue", ctx, exchangeName, queue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveQueue indicates an expected call of SaveQueue.
func (mr *MockRepositoryMockRecorder) SaveQueue(ctx, exchangeName, queue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQueue", reflect.TypeOf((*MockRepository)(nil).SaveQueue), ctx, exchangeName, queue)
}

// SaveReadyDelivery mocks base method.
func (m *MockRepository) SaveReadyDelivery(ctx context.Context, exchangeName, queueName string, delivery core.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReadyDelivery", ctx, exchangeName, queueName, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveReadyDelivery indicates an expected call of SaveReadyDelivery.
func (mr *MockRepositoryMockRecorder) SaveReadyDelivery(ctx, exchangeName, queueName, delivery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReadyDelivery", reflect.TypeOf((*MockRepository)(nil).SaveReadyDelivery), ctx, exchangeName, queueName, delivery)
}
